### ISSUE TITLE
behavior is null

### ISSUE THREAD

**Issue by phidias51** [expandjs/mat-paper#1]
I see the following warning in my log: 
 [mat-paper::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
polymer-micro.html:235 

http://localhost:9000/bower_components/xp-shared-behavior/xp-shared-behavior.html 404 (Not Found)

I'm only using the mat-dropdown component.  So I assume this is some dependency that isn't in the mat-dropdown bower file.

**Comment by Pupix** [comment]
Thanks for finding this bug!

Yes, that's the case indeed. There are some missing dependencies which slipped as we mostly use the entire "mat/xp-elements" import.

A fix will land soon, in the mean time you can download the "mat-elements" and "xp-elements" package and should give you all the needed dependencies.

**Comment by Pupix** [comment]
The issue should be fixed with the new v0.9.4.
